---
name: Commit Linter

on:
    push:
        branches:
            - main
    pull_request:
        types:
            - opened
            - reopened
            - synchronize

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    lint-commits:
        if: ${{ !contains(github.event.head_commit.message, 'bump(release)') }}
        permissions:
            contents: read # for actions/checkout to fetch code
            pull-requests: read # for wagoid/commitlint-github-action to get commits in PR
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                  fetch-depth: 0

            - name: Lint commits
              uses: wagoid/commitlint-github-action@v6
